### ISSUE TITLE
Time "Noting"

### ISSUE THREAD

**Issue by Boosteblume** [marcjulianschwarz/personio-raycast#2]
As a User I want to write down my start time but not commit it to personio. 
I want to see this start time later at the day when I commit my hours.

**Comment by Boosteblume** [comment]
I see two possible solutions here.

Either we store the values for 24h or alternatively we build functions to submit just a start / and just an end time.

Unfortunately I think that the only option we have is to store the values because the API requires a start and a end date.

**Comment by marcjulianschwarz** [comment]
Option 1 is the way to go. 

For storing we could use [Raycasts Caching implementation](https://developers.raycast.com/api-reference/cache), that way we don't have to deal with any file operations.

Also see #17 for more data that we should store in the cache.

**Comment by Boosteblume** [comment]
@marcjulianschwarz Is this issue closed with your last comit?

**Comment by marcjulianschwarz** [comment]
@Boosteblume, no but you can use parts of it to implement this feature.
