### ISSUE TITLE
year selection for attendances

### ISSUE THREAD

**Issue by marcjulianschwarz** [marcjulianschwarz/personio-raycast#23]
Either add a preference to select the year for the attendances command or automatically use the current year instead of the hard-coded "2024" value.

**Comment by Boosteblume** [comment]
additionally could be expanded to select one year or month and year

**Comment by marcjulianschwarz** [comment]
yes, we could probably do something like start-date / end-date to set the period.

**Comment by marcjulianschwarz** [comment]
![personio 2024-04-08 at 10 10 37](https://github.com/marcjulianschwarz/personio-raycast/assets/67844154/a8766519-2c31-49ec-8c13-8f804be29bfa)

I made it automatically select the current year and added a month selection. I think most users would want to see how much they worked in a specific month and do not need a detailed selection of day-accurate dates.
